AWSTemplateFormatVersion: '2010-09-09'

Resources:

  EC2Role:

    Type: AWS::IAM::Role

    Properties:

      RoleName: EC2Role

      AssumeRolePolicyDocument:

        Version: '2012-10-17'

        Statement:

          - Effect: Allow

            Principal:

              Service:

                - ec2.amazonaws.com

            Action:

              - sts:AssumeRole

      Path: /

      Policies:

        - PolicyName: root

          PolicyDocument:

            Version: '2012-10-17'

            Statement:

              - Effect: Allow

                Action:

                  - ec2:*

                  - dynamodb:*

                  - s3:*

                  - sns:*

                  - cloudformation:*

                  - cloudwatch:Describe*

                  - iam:List*

                  - iam:Get*

                Resource: '*'

  EC2Profile:

    Type: AWS::IAM::InstanceProfile

    DependsOn: EC2Role

    Properties:

      Path: /

      Roles:

        - !Ref 'EC2Role'

      InstanceProfileName: EC2Profile



Outputs:

  REGION:

    Value: !Ref "AWS::Region"  
